blueprint:
  name: Cover
  description: Set position of cover based on position of the window, weather condition, temperature and the state of the sun.
  domain: automation
  input:
    outside_temperature_sensor:
      name: Outside temperature sensor
      description: Sensor that gives the temperature from outside.
      selector:
        entity:
          filter:
            - domain: sensor
    outside_temperature_max:
      name: Outside temperature maximum
      description: Maximum outside temperature for closing the cover.
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: "°C"
          mode: box
    room_cover:
      name: Cover
      description: Cover of the room.
      selector:
        entity:
          filter:
            - domain: cover
    window_entity:
      name: Window Entity
      description: Window entity that should be checked.
      selector:
        entity:
          filter:
            - domain: input_select
    window_entity_time:
      name: Window Open Time
      description: Window entity open for (in seconds).
      default: 1
      selector:
        number:
          min: 0
          max: 120
          mode: box
    weather_entity:
      name: Weather entity
      description: Weather entity to check weather condition.
      selector:
        entity:
          filter:
            - domain: weather
    sunset_offset:
      name: Sunset offset
      description: Offset for the sunset. Format should be "00:00:00".
      default: "00:00:00"
      selector:
        text:
    check_sleeping:
      name: Check sleeping
      description: Whether to check the sleeping condition or not.
      default: true
      selector:
        boolean:
    close_cover:
      name: Close cover
      description: Whether to close the cover completely or not.
      default: true
      selector:
        boolean:
    close_cover_to_position:
      name: Close cover to position
      description: Whether to close the cover to a position or not.
      default: false
      selector:
        boolean:
    close_cover_to_position_number:
      name: Close cover position
      description: Number to what the cover should be set when closed.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          mode: box
    additional_conditions:
      name: Additional conditions
      description: Additional conditions for opening cover.
      default:
        - condition: template
          value_template: "{{ true }}"
      selector:
        condition:
    additional_triggers:
      name: Additional triggers
      default: [ ]
      selector:
        trigger:

mode: restart

triggers:
  - trigger: state
    entity_id:
      - !input window_entity
    id: window_open
    to: Open
    for:
      seconds: !input window_entity_time
  - trigger: state
    entity_id:
      - !input window_entity
    id: window_tilted
    to: Tilted
    for:
      seconds: !input window_entity_time
  - trigger: state
    entity_id:
      - !input window_entity
    to: Closed
    id: window_closed
  - trigger: numeric_state
    entity_id:
      - !input outside_temperature_sensor
    below: 0
  - trigger: numeric_state
    entity_id:
      - !input outside_temperature_sensor
    above: !input outside_temperature_max
    id: above_outside_max
  - trigger: sun
    event: sunset
    offset: !input sunset_offset
    id: sunset
  - trigger: state
    entity_id:
      - input_boolean.sleeping
    id: sleeping
  - triggers: !input additional_triggers

actions:
  - choose:
      - conditions:
          - condition: not
            alias: Window not open (closed or tilted)
            conditions:
              - condition: state
                entity_id: !input window_entity
                state: Open
          - condition: numeric_state
            entity_id: !input room_cover
            attribute: current_position
            above: 0
          - condition: or
            conditions:
              - condition: and
                alias: Outside below 0 and sun is gone
                conditions:
                  - condition: numeric_state
                    entity_id: !input outside_temperature_sensor
                    below: 0
                  - condition: sun
                    before: sunrise
                    after: sunset
              - condition: state
                entity_id: input_boolean.sleeping
                state: "on"
                enabled: !input check_sleeping
                alias: Sleeping on
              - condition: and
                alias: Outside above maximum defined and sun still there
                conditions:
                  - condition: sun
                    after: sunrise
                    after_offset: "02:00:00"
                    before: sunset
                    before_offset: !input sunset_offset
                  - condition: numeric_state
                    entity_id: !input outside_temperature_sensor
                    above: !input outside_temperature_max
                    alias: Outside above max input temperature
                  - condition: or
                    alias: Check weather condition
                    conditions:
                      - condition: state
                        entity_id: !input weather_entity
                        state: "sunny"
                        alias: Sunny
                      - condition: state
                        entity_id: !input weather_entity
                        state: "partlycloudy"
                        alias: Partly cloudy
                      - condition: state
                        entity_id: !input weather_entity
                        state: "cloudy"
                        alias: Cloudy
        sequence:
          - alias: Close or set position on cover
            enabled: !input close_cover
            if:
              - condition: state
                entity_id: !input window_entity
                state: Tilted
            then:
              - action: cover.set_cover_position
                metadata: { }
                data:
                  position: 65
                target:
                  entity_id: !input room_cover
            else:
              - action: cover.close_cover
                metadata: { }
                data: { }
                target:
                  entity_id: !input room_cover
          - action: cover.set_cover_position
            metadata: { }
            data:
              position: !input close_cover_to_position_number
            target:
              entity_id: !input room_cover
            enabled: !input close_cover_to_position
        alias: Close cover
      - conditions:
          - alias: Window open or Sunset/Temperature
            condition: or
            conditions:
              - condition: state
                entity_id: !input window_entity
                state: Open
                alias: Window open
                for:
                  seconds: !input window_entity_time
              - condition: state
                entity_id: !input window_entity
                state: Tilted
                alias: Window tilted
                for:
                  seconds: !input window_entity_time
              - condition: and
                alias: Check temperature, sleeping and additional
                conditions:
                  - condition: or
                    alias: Outside below maximum defined or sun gone
                    conditions:
                      - condition: numeric_state
                        entity_id: !input outside_temperature_sensor
                        below: !input outside_temperature_max
                        alias: Outside below maximum defined
                      - condition: sun
                        alias: After sunset (with offset)
                        before: sunrise
                        before_offset: "02:00:00"
                        after: sunset
                        after_offset: !input sunset_offset
                  - condition: state
                    entity_id: input_boolean.sleeping
                    state: "off"
                    alias: Sleeping is off
                  - condition: or
                    conditions: !input additional_conditions
          - condition: numeric_state
            entity_id: !input room_cover
            attribute: current_position
            below: 100
        sequence:
          - alias: Open or set position on cover
            if:
              - condition: or
                alias: Tilted or cover should be closed
                conditions:
                  - condition: and
                    alias: Tilted and sleeping
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: Tilted
                        alias: Window tilted
                        for:
                          seconds: !input window_entity_time
                      - condition: state
                        entity_id: input_boolean.sleeping
                        state: "on"
                        enabled: !input check_sleeping
                        alias: Sleeping on
                  - condition: and
                    alias: Outside above maximum defined and sun still there
                    conditions:
                      - condition: sun
                        after: sunrise
                        after_offset: "02:00:00"
                        before: sunset
                        before_offset: !input sunset_offset
                      - condition: numeric_state
                        entity_id: !input outside_temperature_sensor
                        above: !input outside_temperature_max
                        alias: Outside above max input temperature
                      - condition: or
                        alias: Check weather condition
                        conditions:
                          - condition: state
                            entity_id: !input weather_entity
                            state: "sunny"
                            alias: Sunny
                          - condition: state
                            entity_id: !input weather_entity
                            state: "partlycloudy"
                            alias: Partly cloudy
                          - condition: state
                            entity_id: !input weather_entity
                            state: "cloudy"
                            alias: Cloudy
            then:
              - action: cover.set_cover_position
                metadata: { }
                data:
                  position: 65
                target:
                  entity_id: !input room_cover
            else:
              - action: cover.open_cover
                metadata: { }
                data: { }
                target:
                  entity_id: !input room_cover
        alias: Open cover
