blueprint:
  name: Smart Cover Control
  description: Automatically control cover based on window state, temperature, and sleeping mode.
  domain: automation
  input:
    outside_temperature_sensor:
      name: Outside Temperature Sensor
      selector:
        entity:
          filter:
            - domain: sensor
      default: "sensor.outdoor_temperature"
    indoor_temperature_sensor:
      name: Indoor Temperature Sensor
      description: Median temperature of rooms with windows
      selector:
        entity:
          filter:
            - domain: sensor
      default: "sensor.indoor_temperature"
    outside_temperature_max:
      name: Maximum Temperature (°C)
      description: Close cover when temperature exceeds this value
      default: 22
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    outside_temperature_min:
      name: Minimum Temperature (°C)
      description: Open cover when temperature drops below this value
      default: 19
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    sun_elevation_min:
      name: Minimum Sun Elevation (°)
      description: Minimum sun elevation angle to trigger hot day conditions
      default: 15
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "°"
    sun_azimuth_min:
      name: Minimum Sun Azimuth (°)
      description: Minimum sun azimuth angle (when sun starts hitting windows)
      default: 150
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    sun_azimuth_max:
      name: Maximum Sun Azimuth (°)
      description: Maximum sun azimuth angle (when sun stops hitting windows)
      default: 240
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    room_cover:
      name: Cover Entity
      selector:
        entity:
          filter:
            - domain: cover
    window_entity:
      name: Window Entity
      selector:
        entity:
          filter:
            - domain: input_select
    sunshine_entity:
      name: Sunshine Entity
      selector:
        entity:
          filter:
            - domain: binary_sensor
      default: "binary_sensor.sunshine"
    window_entity_time:
      name: Window Open Time
      description: Window entity open for (in seconds).
      default: 1
      selector:
        number:
          min: 0
          max: 120
          mode: box
    sleeping_entity:
      name: Sleeping Entity
      description: Sleeping entity to monitor
      default: "input_boolean.sleeping"
      selector:
        entity:
          filter:
            - domain: input_boolean
    close_cover:
      name: Close cover
      description: Whether to close the cover completely or not.
      default: true
      selector:
        boolean:
    close_cover_to_position:
      name: Close cover to position
      description: Whether to close the cover to a position or not.
      default: false
      selector:
        boolean:
    check_sleeping:
      name: Check sleeping or not
      description: Whether to check sleeping state or not.
      default: true
      selector:
        boolean:
    close_cover_to_position_when_sleeping_and_tilted_number:
      name: Close cover position when sleeping and tilted
      description: Number to what the cover should be set when tilted and sleeping is on.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          mode: box
    close_cover_to_position_number:
      name: Close cover position
      description: Number to what the cover should be set when closed.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          mode: box
    check_cold_outside:
      name: Check cold outside or not
      description: Whether to check cold temperature state or not.
      default: false
      selector:
        boolean:
    additional_trigger:
      name: Additional triggers
      description: Additional triggers for the automation. Leave default if not needed.
      default:
        - platform: template
          value_template: "{{ false }}"
      selector:
        trigger:
    use_additional_conditions_closing:
      name: Use additional closing conditions
      description: Enable additional conditions for closing the cover.
      default: false
      selector:
        boolean:
    additional_conditions_closing:
      name: Additional conditions for closing
      description: Additional conditions that must be met for closing cover.
      default: []
      selector:
        condition:
    use_additional_conditions_opening:
      name: Use additional opening conditions
      description: Enable additional conditions for opening the cover.
      default: false
      selector:
        boolean:
    additional_conditions_opening:
      name: Additional conditions for opening
      description: Additional conditions that must be met for opening cover.
      default: []
      selector:
        condition:

variables:
  close_cover_to_position_when_sleeping_and_tilted_number: !input close_cover_to_position_when_sleeping_and_tilted_number
  close_cover_to_position_number: !input close_cover_to_position_number
  room_cover: !input room_cover
  sleeping_entity: !input sleeping_entity
  check_sleeping: !input check_sleeping
  close_cover: !input close_cover
  close_cover_to_position: !input close_cover_to_position
  check_cold_outside: !input check_cold_outside
  use_additional_conditions_closing: !input use_additional_conditions_closing
  use_additional_conditions_opening: !input use_additional_conditions_opening
  
  current_position: "{{ state_attr(room_cover, 'current_position') | int(0) }}"
  is_sleeping: "{{ is_state(sleeping_entity, 'on') and check_sleeping }}"
  
  window_entity: !input window_entity
  outside_temp_sensor: !input outside_temperature_sensor
  indoor_temp_sensor: !input indoor_temperature_sensor
  outside_temp_max: !input outside_temperature_max
  outside_temp_min: !input outside_temperature_min
  sun_elev_min: !input sun_elevation_min
  sun_az_min: !input sun_azimuth_min
  sun_az_max: !input sun_azimuth_max
  sunshine_entity: !input sunshine_entity

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input window_entity
    for:
      seconds: !input window_entity_time
    id: window_changed

  - platform: state
    entity_id: !input sleeping_entity
    id: sleeping_changed

  - platform: state
    entity_id: !input sunshine_entity
    for:
      minutes: 5
    id: sunshine_changed

  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    above: !input outside_temperature_max
    for:
      minutes: 10
    id: temp_above_max

  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: !input outside_temperature_min
    for:
      minutes: 10
    id: temp_below_min

  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: 3
    for:
      minutes: 10
    id: temp_freezing

  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: !input sun_azimuth_min
    id: sun_enters_window

  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: !input sun_azimuth_max
    id: sun_leaves_window

  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: !input sun_elevation_min
    id: sun_high_enough

  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -10
    id: sun_well_below_horizon

  - triggers: !input additional_trigger
    id: additional

action:
  - choose:
      # ============================================
      # PRIORITY 1: Sleeping mode
      # ============================================
      - conditions:
          - condition: template
            value_template: "{{ is_sleeping }}"
        sequence:
          - choose:
              # Sleeping + Window Closed → Close cover fully
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Closed"
                sequence:
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ not use_additional_conditions_closing }}"
                      - condition: and
                        conditions: !input additional_conditions_closing
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

              # Sleeping + Window Tilted → Partial close
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Tilted"
                sequence:
                  - condition: template
                    value_template: "{{ current_position != close_cover_to_position_when_sleeping_and_tilted_number }}"
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ not use_additional_conditions_closing }}"
                      - condition: and
                        conditions: !input additional_conditions_closing
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: "{{ close_cover_to_position_when_sleeping_and_tilted_number }}"

              # Sleeping + Window Open → Open cover
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Open"
                sequence:
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    below: 100
                  - service: cover.open_cover
                    target:
                      entity_id: !input room_cover

      # ============================================
      # PRIORITY 2: Hot sunny day
      # ============================================
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: !input sun_elevation_min
          - condition: numeric_state
            entity_id: sun.sun
            attribute: azimuth
            above: !input sun_azimuth_min
          - condition: numeric_state
            entity_id: sun.sun
            attribute: azimuth
            below: !input sun_azimuth_max
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            above: !input outside_temperature_max
          - condition: state
            entity_id: !input sunshine_entity
            state: "on"
          - condition: template
            value_template: >
              {{ states(outside_temp_sensor) | float(0) > 
                 states(indoor_temp_sensor) | float(100) - 3 }}
        sequence:
          - choose:
              # Window open/tilted during hot day → partial close
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                sequence:
                  - condition: template
                    value_template: "{{ current_position != 55 }}"
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ not use_additional_conditions_closing }}"
                      - condition: and
                        conditions: !input additional_conditions_closing
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55

            # Window closed during hot day → close cover
            default:
              - condition: or
                conditions:
                  - condition: template
                    value_template: "{{ not use_additional_conditions_closing }}"
                  - condition: and
                    conditions: !input additional_conditions_closing
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ close_cover_to_position }}"
                    sequence:
                      - condition: template
                        value_template: "{{ current_position != close_cover_to_position_number }}"
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: "{{ close_cover_to_position_number }}"
                default:
                  - condition: template
                    value_template: "{{ close_cover }}"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

      # ============================================
      # PRIORITY 3: Cold night
      # ============================================
      - conditions:
          - condition: template
            value_template: "{{ check_cold_outside }}"
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            below: 3
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: -10
        sequence:
          - choose:
              # Window open/tilted during cold night → partial close
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                sequence:
                  - condition: template
                    value_template: "{{ current_position != 55 }}"
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ not use_additional_conditions_closing }}"
                      - condition: and
                        conditions: !input additional_conditions_closing
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55

            default:
              - condition: or
                conditions:
                  - condition: template
                    value_template: "{{ not use_additional_conditions_closing }}"
                  - condition: and
                    conditions: !input additional_conditions_closing
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ close_cover_to_position }}"
                    sequence:
                      - condition: template
                        value_template: "{{ current_position != close_cover_to_position_number }}"
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: "{{ close_cover_to_position_number }}"
                default:
                  - condition: template
                    value_template: "{{ close_cover }}"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

    # ============================================
    # DEFAULT: Open cover
    # ============================================
    default:
      - condition: template
        value_template: "{{ not is_sleeping }}"
      
      - condition: numeric_state
        entity_id: !input room_cover
        attribute: current_position
        below: 100
      
      - condition: or
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input window_entity
                state: "Open"
              - condition: state
                entity_id: !input window_entity
                state: "Tilted"
          
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: !input outside_temperature_sensor
                below: !input outside_temperature_min
              - condition: or
                conditions:
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: azimuth
                    above: !input sun_azimuth_max
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: azimuth
                    below: !input sun_azimuth_min
                  - condition: state
                    entity_id: !input sunshine_entity
                    state: "off"
      
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ not use_additional_conditions_opening }}"
          - condition: and
            conditions: !input additional_conditions_opening
      
      - service: cover.open_cover
        target:
          entity_id: !input room_cover