blueprint:
  name: Smart Cover Control
  description: Automatically control cover based on window state, weather, temperature, and sleeping mode.
  domain: automation
  input:
    outside_temperature_sensor:
      name: Outside Temperature Sensor
      selector:
        entity:
          filter:
            - domain: sensor
    outside_temperature_max:
      name: Maximum Temperature (°C)
      description: Close cover when temperature exceeds this value
      default: 25
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    room_cover:
      name: Cover Entity
      selector:
        entity:
          filter:
            - domain: cover
    window_entity:
      name: Window Entity
      selector:
        entity:
          filter:
            - domain: input_select
    weather_entity:
      name: Weather Entity
      selector:
        entity:
          filter:
            - domain: weather
    sunrise_offset:
      name: Sunrise Offset
      description: Format should be "HH:MM:SS"
      default: "02:00:00"
      selector:
        text:
    sunset_offset:
      name: Sunset Offset
      description: Format should be "HH:MM:SS"
      default: "01:00:00"
      selector:
        text:
    window_entity_time:
      name: Window Open Time
      description: Window entity open for (in seconds).
      default: 1
      selector:
        number:
          min: 0
          max: 120
          mode: box
    close_cover:
      name: Close cover
      description: Whether to close the cover completely or not.
      default: true
      selector:
        boolean:
    close_cover_to_position:
      name: Close cover to position
      description: Whether to close the cover to a position or not.
      default: false
      selector:
        boolean:
    close_cover_to_position_number:
      name: Close cover position
      description: Number to what the cover should be set when closed.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          mode: box
    additional_conditions:
      name: Additional conditions
      description: Additional conditions for opening cover.
      default:
        - condition: template
          value_template: "{{ true }}"
      selector:
        condition:

mode: restart

trigger:
  - platform: state
    entity_id: !input window_entity
    for:
      seconds: !input window_entity_time
  - platform: state
    entity_id: input_boolean.sleeping
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    above: !input outside_temperature_max
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: !input outside_temperature_max
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: 0
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
  - platform: sun
    event: sunset
    offset: !input sunset_offset
  - trigger: state
    entity_id:
      - input_boolean.sleeping
    id: sleeping

action:
  - choose:
      # Priority 1: Sleeping mode - cover follows window state exactly
      - conditions:
          - condition: state
            entity_id: input_boolean.sleeping
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Closed"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Tilted"
                  - condition: not
                    conditions:
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        above: 84
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        below: 86
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 85
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Open"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    below: 100
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input room_cover

      # Priority 2: Hot sunny day during daytime
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: !input sunrise_offset
            before: sunset
            before_offset: !input sunset_offset
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            above: !input outside_temperature_max
          - condition: or
            conditions:
              - condition: state
                entity_id: !input weather_entity
                state: "sunny"
              - condition: state
                entity_id: !input weather_entity
                state: "partlycloudy"
              - condition: state
                entity_id: !input weather_entity
                state: "cloudy"
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                  - condition: not
                    conditions:
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        above: 54
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        below: 56
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: !input close_cover_to_position
                    sequence:
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: !input close_cover_to_position_number
                default:
                  - condition: template
                    value_template: "{{ is_state('!input close_cover', 'true') }}"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

      # Priority 3: Cold and sun is gone (below horizon)
      - conditions:
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            below: 0
          - condition: sun
            before: sunrise
            after: sunset
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                  - condition: not
                    conditions:
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        above: 54
                      - condition: numeric_state
                        entity_id: !input room_cover
                        attribute: current_position
                        below: 56
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: !input close_cover_to_position
                    sequence:
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: !input close_cover_to_position_number
                default:
                  - condition: template
                    value_template: "{{ is_state('!input close_cover', 'true') }}"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

    # Default: Open cover for normal conditions
    default:
      - condition: numeric_state
        entity_id: !input room_cover
        attribute: current_position
        below: 100
      - service: cover.open_cover
        target:
          entity_id: !input room_cover