blueprint:
  name: Smart Cover Control
  description: Automatically control cover based on window state, temperature, and sleeping mode.
  domain: automation
  input:
    outside_temperature_sensor:
      name: Outside Temperature Sensor
      selector:
        entity:
          filter:
            - domain: sensor
      default: "sensor.outdoor_temperature"
    indoor_temperature_sensor:
      name: Indoor Temperature Sensor
      description: Median temperature of rooms with windows
      selector:
        entity:
          filter:
            - domain: sensor
      default: "sensor.indoor_temperature"
    outside_temperature_max:
      name: Maximum Temperature (°C)
      description: Close cover when temperature exceeds this value
      default: 22
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    outside_temperature_min:
      name: Minimum Temperature (°C)
      description: Open cover when temperature drops below this value
      default: 19
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    sun_elevation_min:
      name: Minimum Sun Elevation (°)
      description: Minimum sun elevation angle to trigger hot day conditions
      default: 15
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "°"
    sun_azimuth_min:
      name: Minimum Sun Azimuth (°)
      description: Minimum sun azimuth angle (when sun starts hitting windows)
      default: 150
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    sun_azimuth_max:
      name: Maximum Sun Azimuth (°)
      description: Maximum sun azimuth angle (when sun stops hitting windows)
      default: 240
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    room_cover:
      name: Cover Entity
      selector:
        entity:
          filter:
            - domain: cover
    window_entity:
      name: Window Entity
      selector:
        entity:
          filter:
            - domain: input_select
    sunshine_entity:
      name: Sunshine Entity
      selector:
        entity:
          filter:
            - domain: binary_sensor
      default: "binary_sensor.sunshine"
    window_entity_time:
      name: Window Open Time
      description: Window entity open for (in seconds).
      default: 1
      selector:
        number:
          min: 0
          max: 120
          mode: box
    sleeping_entity:
      name: Sleeping Entity
      description: Sleeping entity to monitor
      default: "input_boolean.sleeping"
      selector:
        entity:
          filter:
            - domain: input_boolean
    close_cover:
      name: Close cover
      description: Whether to close the cover completely or not.
      default: true
      selector:
        boolean:
    close_cover_to_position:
      name: Close cover to position
      description: Whether to close the cover to a position or not.
      default: false
      selector:
        boolean:
    check_sleeping:
      name: Check sleeping or not
      description: Whether to check sleeping state or not.
      default: true
      selector:
        boolean:
    close_cover_to_position_when_sleeping_and_tilted_number:
      name: Close cover position when sleeping and tilted
      description: Number to what the cover should be set when tilted and sleeping is on.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          mode: box
    close_cover_to_position_number:
      name: Close cover position
      description: Number to what the cover should be set when closed.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          mode: box
    additional_trigger:
      name: Additional triggers
      description: Additional triggers for the automation.
      default:
      selector:
        trigger:
    additional_conditions_closing:
      name: Additional conditions for closing
      description: Additional conditions for closing cover.
      default:
        - condition: template
          value_template: "{{ true }}"
      selector:
        condition:
    additional_conditions:
      name: Additional conditions
      description: Additional conditions for opening cover.
      default:
        - condition: template
          value_template: "{{ true }}"
      selector:
        condition:

mode: restart

trigger:
  - triggers: !input additional_trigger
  - platform: state
    entity_id: !input window_entity
    for:
      seconds: !input window_entity_time
  - platform: state
    entity_id: !input sleeping_entity
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    above: !input outside_temperature_max
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: !input outside_temperature_min
  - platform: numeric_state
    entity_id: !input outside_temperature_sensor
    below: 0
  - platform: state
    entity_id: !input sunshine_entity
    to: "on"
  - platform: state
    entity_id: !input sunshine_entity
    to: "off"
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: !input sun_elevation_min
  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: !input sun_azimuth_min
  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    below: !input sun_azimuth_min
  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: !input sun_azimuth_max
  - platform: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    below: !input sun_azimuth_max

action:
  - choose:
      # Priority 1: Sleeping mode - cover follows window state
      - conditions:
          - condition: state
            entity_id: !input sleeping_entity
            state: "on"
          - condition: template
            value_template: !input check_sleeping
          - condition: and
            conditions: !input additional_conditions_closing
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Closed"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Tilted"
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: !input close_cover_to_position_when_sleeping_and_tilted_number
              - conditions:
                  - condition: state
                    entity_id: !input window_entity
                    state: "Open"
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    below: 100
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input room_cover

      # Priority 2: Hot sunny day during daytime
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: !input sun_elevation_min
          - condition: numeric_state
            entity_id: sun.sun
            attribute: azimuth
            above: !input sun_azimuth_min
          - condition: numeric_state
            entity_id: sun.sun
            attribute: azimuth
            below: !input sun_azimuth_max
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            above: !input outside_temperature_max
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            value_template: "{{ float(state.state) + 3 }}"
            above: !input indoor_temperature_sensor
          - condition: state
            entity_id: !input sunshine_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: !input close_cover_to_position
                    sequence:
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: !input close_cover_to_position_number
                default:
                  - condition: template
                    value_template: !input close_cover
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

      # Priority 3: Cold nighttime - close cover
      - conditions:
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            below: 0
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 0
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input window_entity
                        state: "Open"
                      - condition: state
                        entity_id: !input window_entity
                        state: "Tilted"
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input room_cover
                    data:
                      position: 55
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: !input close_cover_to_position
                    sequence:
                      - service: cover.set_cover_position
                        target:
                          entity_id: !input room_cover
                        data:
                          position: !input close_cover_to_position_number
                default:
                  - condition: template
                    value_template: !input close_cover
                  - condition: numeric_state
                    entity_id: !input room_cover
                    attribute: current_position
                    above: 0
                  - service: cover.close_cover
                    target:
                      entity_id: !input room_cover

    # Default: Open cover for normal conditions
    default:
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: !input outside_temperature_sensor
            below: !input outside_temperature_min
          - condition: or
            conditions:
              - condition: state
                entity_id: !input window_entity
                state: "Open"
              - condition: state
                entity_id: !input window_entity
                state: "Tilted"
          - condition: state
            entity_id: !input sunshine_entity
            state: "off"
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation_min
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sun.sun
                attribute: azimuth
                below: !input sun_azimuth_min
              - condition: numeric_state
                entity_id: sun.sun
                attribute: azimuth
                above: !input sun_azimuth_max
      - condition: numeric_state
        entity_id: !input room_cover
        attribute: current_position
        below: 100
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: !input room_cover
            attribute: current_position
            below: !input close_cover_to_position_when_sleeping_and_tilted_number
          - condition: numeric_state
            entity_id: !input room_cover
            attribute: current_position
            below: !input close_cover_to_position
      - condition: or
        conditions: !input additional_conditions
      - service: cover.open_cover
        target:
          entity_id: !input room_cover