blueprint:
  name: Present Light
  description: Turn a light/plug on and off based on detected presents/motion.
  domain: automation
  input:
    occupied_binary_sensor:
      name: Occupied Sensor
      description: Sensor that indicates if the room is occupied.
      selector:
        entity:
          filter:
            - domain: binary_sensor
    additional_trigger:
      name: Additional Trigger
      description: Additional Triggers can be configured here. For example checking a light sensor.
      default:
      selector:
        trigger:
    condition_on:
      name: Condition On
      description: Additional conditions for turning on the devices.
      default: [ ]
      selector:
        condition:
    condition_off:
      name: Condition Off
      description: Additional conditions for turning off the devices.
      default: [ ]
      selector:
        condition:
    no_occupancy_wait:
      name: Wait time
      description: Wait time for turning off the light/switch.
      default: 0
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    light_target:
      name: Light Target
      description: Light that should be turned on/off.
      default: { }
      selector:
        target:
          entity:
            domain: light
    switch_target:
      name: Switch Target
      description: Switch that should be turned on/off.
      default: { }
      selector:
        target:
          entity:
            domain: switch
    additional_actions_on:
      name: Additional Actions On
      description: Additional actions which should run when devices are turned on.
      default: [ ]
      selector:
        action:
    additional_actions_off:
      name: Additional Actions Off
      description: Additional actions which should run when devices are turned off.
      default: [ ]
      selector:
        action:

mode: restart

triggers:
  - trigger: state
    entity_id: !input occupied_binary_sensor
  - triggers: !input additional_trigger

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input occupied_binary_sensor
            state: "on"
          - condition: and
            conditions: !input condition_on
        sequence:
          - sequence: !input additional_actions
          - action: switch.turn_on
            target: !input switch_target
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input occupied_binary_sensor
                state: "off"
              - condition: or
                conditions: !input condition_off
        sequence:
          - delay: !input no_occupancy_wait
          - action: switch.turn_off
            target: !input switch_target
          - sequence: !input additional_actions
