blueprint:
  name: Present Light
  description: Turn a light/plug on and off based on detected presents/motion.
  domain: automation
  input:
    occupied_binary_sensor:
      name: Occupied Sensor
      description: Sensor that indicates if the room is occupied.
      selector:
        entity:
          filter:
            - domain: binary_sensor
    additional_trigger:
      name: Additional Trigger
      description: Additional Triggers can be configured here. For example checking a light sensor.
      default: [ ]
      selector:
        trigger:
    illuminance_condition_below:
      name: Illuminance Condition Below
      description: Threshold for turning on the devices.
      default:
        condition: numeric_state
        below: 50
      selector:
        condition:
    illuminance_condition_above:
      name: Illuminance Condition Above
      description: Threshold for turning off the devices.
      default:
        condition: numeric_state
        above: 100
      selector:
        condition:
    no_occupancy_wait:
      name: Wait time
      description: Wait time for turning off the light/switch.
      default: 0
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    light_target:
      name: Light Target
      description: Light that should be turned on/off.
      default: { }
      selector:
        target:
          entity:
            domain: light
    switch_target:
      name: Switch Target
      description: Switch that should be turned on/off.
      default: { }
      selector:
        target:
          entity:
            domain: switch
    additional_action_condition:
      name: Additional Action Condition
      description: Conditions for additional turn on of devices.
      default: [ ]
      selector:
        condition:
    additional_light_target:
      name: Additional Light Target
      description: Light that should be turned on/off additionally.
      default: { }
      selector:
        target:
          entity:
            domain: light
    additional_switch_target:
      name: Additional Switch Target
      description: Switch that should be turned on/off additionally.
      default: { }
      selector:
        target:
          entity:
            domain: switch
    home_or_guest_required:
      name: Enable Home or Guest
      description: Should the Home and Guest sensor be checked?
      default: true
      selector:
        boolean:
    guest_mode_binary_sensor:
      name: Guest Mode Sensor
      description: Sensor that indicates if guest mode is on.
      selector:
        entity:
          filter:
            - domain:
                - binary_sensor
                - switch
    home_sensor:
      name: Home Sensor
      description: Sensor that indicates if persons are home.
      default: zone.home
      selector:
        entity:
          filter:
            - domain: sensor

mode: restart

triggers:
  - trigger: state
    entity_id: !input occupied_binary_sensor
  - !input additional_trigger

actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input guest_mode_binary_sensor
                state: "on"
              - condition: numeric_state
                entity_id: !input home_sensor
                above: 0
            alias: Home or Guest-Mode
          - condition: and
            enabled: !input home_or_guest_required
            conditions:
              - condition: state
                entity_id: !input occupied_binary_sensor
                state: "on"
              - condition: !input illuminance_condition_below
            alias: Occupied and light below threshold
        sequence:
          - if:
              - condition: !input additional_action_condition
            then:
              - action: switch.turn_on
                target: !input additional_switch_target
              - action: light.turn_on
                target: !input additional_light_target
          - action: switch.turn_on
            target: !input switch_target
          - action: light.turn_on
            target: !input light_target
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input occupied_binary_sensor
                state: "off"
              - condition: !input illuminance_condition_above
            alias: Not occupied or light above threshold
        sequence:
          - delay: !input no_occupancy_wait
          - action: switch.turn_off
            target: !input switch_target
          - action: light.turn_off
            target: !input light_target
          - action: switch.turn_off
            target: !input additional_switch_target
          - action: light.turn_off
            target: !input additional_light_target
