blueprint:
  name: Present Light
  description: Turn a light/plug on and off based on detected presents/motion.
  domain: automation
  input:
    occupied_binary_sensor:
      name: Occupied Sensor
      description: Sensor that indicates if the room is occupied.
      selector:
        entity:
          filter:
            - domain: binary_sensor
    additional_trigger:
      name: Additional Trigger
      description: Additional Triggers can be configured here. For example checking a light sensor.
      default:
      selector:
        trigger:
    condition_on:
      name: Condition On
      description: Additional AND conditions for turning on the devices.
      default: [ ]
      selector:
        condition:
    condition_on_or:
      name: Condition On Or
      description: Additional OR conditions for turning on the devices.
      default: [ ]
      selector:
        condition:
    condition_off:
      name: Condition Off
      description: Additional OR conditions for turning off the devices.
      default: [ ]
      selector:
        condition:
    condition_off_and:
      name: Condition Off And
      description: Additional AND conditions for turning off the devices.
      default: [ ]
      selector:
        condition:
    no_occupancy_wait:
      name: Wait time
      description: Wait time for turning off the light/switch.
      default: 0
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    actions_on:
      name: Actions On
      description: Actions which should run when devices are turned on.
      default: [ ]
      selector:
        action:
    actions_off:
      name: Actions Off
      description: Actions which should run when devices are turned off.
      default: [ ]
      selector:
        action:

mode: restart

triggers:
  - trigger: state
    entity_id: !input occupied_binary_sensor
  - triggers: !input additional_trigger

actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: !input occupied_binary_sensor
                    state: "on"
                  - condition: and
                    conditions: !input condition_on
              - condition: or
                conditions: !input condition_on_or
        sequence: !input actions_on
      - conditions:
          - condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input occupied_binary_sensor
                    state: "off"
                  - condition: or
                    conditions: !input condition_off
              - condition: or
                conditions: !input condition_off_and
        sequence:
          - delay: !input no_occupancy_wait
          - sequence: !input actions_off
