blueprint:
  name: Present Light
  description: Turn a light/plug on and off based on detected presents/motion.
  domain: automation
  input:
    occupied_binary_sensor:
      name: Occupied Sensor
      description: Sensor that indicates if the room is occupied.
      selector:
        entity:
          filter:
            - domain: binary_sensor
    additional_trigger:
      name: Additional Trigger
      description: Additional Triggers can be configured here. For example checking a light sensor.
      default:
      selector:
        trigger:
    condition_on:
      name: Condition On
      description: Additional conditions for turning on the devices.
      default:
        - condition: state
          entity_id: !input occupied_binary_sensor
          state: "on"
      selector:
        condition:
    condition_off:
      name: Condition Off
      description: Additional conditions for turning off the devices.
      default:
        - condition: or
          conditions:
            - condition: state
              entity_id: !input occupied_binary_sensor
              state: "off"
      selector:
        condition:
    no_occupancy_wait:
      name: Wait time
      description: Wait time for turning off the light/switch.
      default: 0
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    actions_on:
      name: Actions On
      description: Actions which should run when devices are turned on.
      default: [ ]
      selector:
        action:
    actions_off:
      name: Actions Off
      description: Actions which should run when devices are turned off.
      default: [ ]
      selector:
        action:

mode: restart

triggers:
  - trigger: state
    entity_id: !input occupied_binary_sensor
  - triggers: !input additional_trigger

actions:
  - choose:
      - conditions: !input condition_on
        sequence: !input actions_on
      - conditions: !input condition_off
        sequence:
          - delay: !input no_occupancy_wait
          - sequence: !input actions_off
